In [1]:
import numpy as np 
import pandas as pd

In [3]:
data = pd.read_csv(r'C:\Users\giris\Desktop\AI IBM\bank.csv')
data.head(30)

age          job   marital  education default  balance housing loan  \
0    59       admin.   married  secondary      no     2343     yes   no   
1    56       admin.   married  secondary      no       45      no   no   
2    41   technician   married  secondary      no     1270     yes   no   
3    55     services   married  secondary      no     2476     yes   no   
4    54       admin.   married   tertiary      no      184      no   no   
5    42   management    single   tertiary      no        0     yes  yes   
6    56   management   married   tertiary      no      830     yes  yes   
7    60      retired  divorced  secondary      no      545     yes   no   
8    37   technician   married  secondary      no        1     yes   no   
9    28     services    single  secondary      no     5090     yes   no   
10   38       admin.    single  secondary      no      100     yes   no   
11   30  blue-collar   married  secondary      no      309     yes   no   
12   29   management   married   tertiary      no      199     yes  yes   
13   46  blue-collar    single   tertiary      no      460     yes   no   
14   31   technician    single   tertiary      no      703     yes   no   
15   35   management  divorced   tertiary      no     3837     yes   no   
16   32  blue-collar    single    primary      no      611     yes   no   
17   49     services   married  secondary      no       -8     yes   no   
18   41       admin.   married  secondary      no       55     yes   no   
19   49       admin.  divorced  secondary      no      168     yes  yes   
20   28       admin.  divorced  secondary      no      785     yes   no   
21   43   management    single   tertiary      no     2067     yes   no   
22   43   management  divorced   tertiary      no      388     yes   no   
23   43  blue-collar   married    primary      no     -192     yes   no   
24   37   unemployed    single  secondary      no      381     yes   no   
25   35  blue-collar    single  secondary      no       40     yes   no   
26   31   technician    single   tertiary      no       22     yes   no   
27   43  blue-collar    single  secondary      no        3     yes   no   
28   31       admin.   married  secondary      no      307     yes   no   
29   28  blue-collar    single  secondary      no      759     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome deposit  
0   unknown    5   may      1042         1     -1         0  unknown     yes  
1   unknown    5   may      1467         1     -1         0  unknown     yes  
2   unknown    5   may      1389         1     -1         0  unknown     yes  
3   unknown    5   may       579         1     -1         0  unknown     yes  
4   unknown    5   may       673         2     -1         0  unknown     yes  
5   unknown    5   may       562         2     -1         0  unknown     yes  
6   unknown    6   may      1201         1     -1         0  unknown     yes  
7   unknown    6   may      1030         1     -1         0  unknown     yes  
8   unknown    6   may       608         1     -1         0  unknown     yes  
9   unknown    6   may      1297         3     -1         0  unknown     yes  
10  unknown    7   may       786         1     -1         0  unknown     yes  
11  unknown    7   may      1574         2     -1         0  unknown     yes  
12  unknown    7   may      1689         4     -1         0  unknown     yes  
13  unknown    7   may      1102         2     -1         0  unknown     yes  
14  unknown    8   may       943         2     -1         0  unknown     yes  
15  unknown    8   may      1084         1     -1         0  unknown     yes  
16  unknown    8   may       541         3     -1         0  unknown     yes  
17  unknown    8   may      1119         1     -1         0  unknown     yes  
18  unknown    8   may      1120         2     -1         0  unknown     yes  
19  unknown    8   may       513         1     -1         0  unknown     yes  
20  unknown    8   

In [4]:
data.education.unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [5]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [8]:
inputs1 = data.iloc[:, :9]
inputs2 = data.iloc[:, 11:13]
inputs3 = data.iloc[:, 14:16]

inputs = inputs1.join(inputs2)
inputs = inputs.join(inputs3)

inputs = np.array(inputs)

outputs = data.iloc[:, -1:].values

In [9]:
inputs

array([[59, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [41, 'technician', 'married', ..., 1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., 2, 0, 'unknown'],
       [43, 'technician', 'married', ..., 2, 5, 'failure'],
       [34, 'technician', 'married', ..., 1, 0, 'unknown']], dtype=object)

In [10]:
outputs

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [12]:
ct = ColumnTransformer([('one', OneHotEncoder(), [1, 2, 3, 4, 6, 7, 8, 12])], remainder = 'passthrough')
inputs = ct.fit_transform(inputs)

In [13]:
inputs.shape

(11162, 37)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(inputs,outputs,test_size = 0.2, random_state = 0)

In [16]:
print('Inputs shape ', inputs.shape)
print('Outputs shape ', outputs.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (11162, 37)
Outputs shape  (11162, 1)
x_train shape  (8929, 37)
x_test shape  (2233, 37)
y_train shape  (8929, 1)
y_test shape (2233, 1)


In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.2483547 ,
        -0.56394809, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.31759131,
        -0.56394809, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  1.76816153,
         0.92827075, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ..., -1.03015141,
         2.04743488, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.41856137,
        -0.56394809, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ...,  1.0296377 ,
        -0.56394809, -0.35888264]])

In [20]:
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.77542752,
        -0.51893725,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.42011029,
        -0.51893725,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.54045968,
        -0.17189116, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ...,  3.37949177,
        -0.17189116, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.88431506,
        -0.51893725, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.13356413,
        -0.17189116, -0.38941612]])